### ISSUE TITLE
Add Interactive Map for Cultural Hotspots

### ISSUE THREAD

**Issue by serenade2400** [ajaynegi45/Uttarakhand-Culture-NewUI#47]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Feature Description

I would like to propose adding an interactive map to highlight Uttarakhand's cultural hotspots, historical places, and famous temples. The map can include clickable markers with descriptions for each location. This will provide users with a more engaging and informative experience while exploring the region's cultural heritage. 

### Would you like to work on this feature?

Yes

### Implementation Plan

We could use Google Maps API or Leaflet.js to implement this feature.

**Comment by ajaynegi45** [comment]
Hi @serenade2400,

Thank you for proposing this exciting feature! I really like the idea of adding an interactive map to highlight Uttarakhand’s cultural hotspots, historical places, and famous temples. This will undoubtedly provide users with a richer, more engaging experience while exploring the cultural heritage of Uttarakhand.

Please make sure that the map displays only the Uttarakhand region, and try to give it a modern, polished look—similar to the map on [this link](https://bento.me/ajaynegi). A sleek and user-friendly design will enhance the overall experience. To further improve functionality, the map should first display all the districts of Uttarakhand with pins or markers. When a user clicks on any district, the map should zoom in on that district and show cultural hotspots, historical places, famous temples, and other relevant information specific to that district.

Resources: 
- [SVG MAP](https://github.com/ajaynegi45/Uttarakhand-Culture-NewUI/blob/main/public/mapUk.svg)
- [Other Resource](https://ajaynegi.notion.site/Resources-f92bcb910d0544a1a8db50cc3ef79cfe)

Before making any contributions, please read the [Readme.md](https://github.com/ajaynegi45/Uttarakhand-Culture-NewUI/blob/main/README.md) file carefully to better understand the project's goals and purpose. This will give you clarity on our mission. Also, make sure to review the [Contributing.md](https://github.com/ajaynegi45/Uttarakhand-Culture-NewUI/blob/main/contributing.md) file, which contains important guidelines to make the contribution process smoother, especially for newcomers.

Feel free to start working on this, and if you need any assistance or guidance along the way, don’t hesitate to reach out!

**Comment by serenade2400** [comment]
Hi ,
I've submitted a pull request for this issue. Could you please assign me to it?
(https://github.com/ajaynegi45/Uttarakhand-Culture-NewUI/pull/60)

Thank you!

**Comment by ajaynegi45** [comment]
> Hi , I've submitted a pull request for this issue. Could you please assign me to it? (#60)
> 
> Thank you!

We have mentioned some comment in it

**Comment by serenade2400** [comment]
i have fixed the issues https://github.com/ajaynegi45/Uttarakhand-Culture-NewUI/pull/63

**Comment by ajaynegi45** [comment]
> i have fixed the issues #63

Check this https://github.com/ajaynegi45/Uttarakhand-Culture-NewUI/pull/63#pullrequestreview-2347245888

**Comment by coderKrysio** [comment]
Hey @ajaynegi45,
Is this issue still available, I see no merged PR where this issue was addressed.

**Comment by ajaynegi45** [comment]
> Hey @ajaynegi45, Is this issue still available, I see no merged PR where this issue was addressed.

This issue is still available. You can ask here https://github.com/ajaynegi45/Uttarakhand-Culture-NewUI/issues/149

**Comment by ajaynegi45** [comment]
Hi @serenade2400,

Hope you're doing great! 😊 Just wanted to check in and see how things are coming along with the issue you're working on. Any progress or updates you’d like to share? And if you’ve run into any roadblocks or need a hand with anything, please don’t hesitate to reach out!

Looking forward to hearing from you!
